### PR TITLE
added api entry point option for fetching user profile for microsoft graph in different c…

### PR DESCRIPTION
**Pull request by leeyuky9802**
The url for auth and token is configurable but not the api entry. Causing the strategy not able to fetch user profile.

different graph may have different api entry:
https://learn.microsoft.com/en-us/previous-versions/office/office-365-api/api/o365-china-endpoints

### CODE REVIEW

**Review by seanfisher — CHANGES_REQUESTED** [review]
Thanks for the PR! I think having this option would be beneficial. Here are a couple of changes I'll request before merging:

- [ ] Remove changes to formatting/punctuation so this PR is narrowly scoped to the relevant change only
- [ ] Add documentation for the new option in the README and example sample application to explain what the option means and how it's used

Thank you.

**Comment by leeyuky9802** [comment]
Hi,
the format changes are reverted and Readme file updated.

**Review by seanfisher — APPROVED** [review]
Thanks for making those updates

**Comment by seanfisher** [comment]
Released in [2.1.0](https://github.com/seanfisher/passport-microsoft/releases/tag/v2.1.0)

**Pull request merged**
