### PR TITLE
removed pkginfo depedency to allow bundling

### PR DESCRIPTION
**Pull request by joelklint**
This package is incompatible when bundling with e.g. `webpack` and `esbuild` as mentioned in https://github.com/seanfisher/passport-microsoft/issues/25. 

This incompatability is unique to this package in comparison to other popular packages. The following is an example of packages which are bundling compatible.
- [`passport`](https://www.npmjs.com/package/passport)
- [`passport-google-oauth20`](https://www.npmjs.com/package/passport-google-oauth20)
- [`express`](https://www.npmjs.com/package/express)
- [`graphql`](https://www.npmjs.com/package/graphql)
- [`jsonwebtoken`](https://www.npmjs.com/package/jsonwebtoken)
- [`luxon`](https://www.npmjs.com/package/luxon)

### CODE REVIEW

**Comment by JoelKlint** [comment]
Hi @seanfisher 👋 

I ran into a bundling problem which I tracked back to this package. As seen in https://github.com/seanfisher/passport-microsoft/issues/25 I am not alone in this experience. I have tried these changes locally in a depending project and it works fine. 

Otherwise great package, thanks! Keep up the good work 🙂

**Comment by len-art** [comment]
Is there any news when will this be merged and published?
Thank you for your work.

**Comment by JoelKlint** [comment]
Considering it has been 171 days without a word from @seanfisher, I do not think it will be anytime soon 🤷

**Comment by joelklint** [comment]
@seanfisher I'm considering closing this PR. Please get back to me if you'd like to have it merged instead

**Comment by seanfisher** [comment]
@joelklint Thanks for the bump. This should be merged. The pkginfo call is vestigial anyway. Planning on releasing a new version today with this change (and some others).

**Pull request merged**
